'use client';

export default function Projects() {
  return (
    <section id="projects" className="py-20 px-4"><div className="max-w-5xl mx-auto"><h2 className="text-3xl font-bold text-white mb-8">Projects</h2><div className="grid md:grid-cols-2 gap-6">
            <div key="Zenflow - Clinical Workflow & Provider Management Dashboard" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Zenflow - Clinical Workflow & Provider Management Dashboard</h3><p className="text-gray-400 mt-2">Architected and developed a comprehensive SaaS dashboard for healthcare provider management, significantly optimizing clinical workflow efficiency. Engineered a low-latency, dynamic weekly scheduling calendar grid, integrated secure operational metrics tables, modular analytics panels, and comprehensive client views to effectively monitor practitioner utilization.</p></div>
            <div key="Solitare - Premium Headless E-Commerce Jewelry Platform" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Solitare - Premium Headless E-Commerce Jewelry Platform</h3><p className="text-gray-400 mt-2">Developed a visually stunning and highly responsive headless e-commerce interface, enabling rich media interaction for a premium luxury jewelry catalog. Implemented advanced features including localized category filters, persistent client-side states, high-fidelity item grids, and seamless customer favorites/wishlist mechanics. Optimized modern asset delivery networks and lazy-loading techniques, achieving a 35% improvement in First Contentful Paint (FCP).</p></div>
            <div key="Pizza – Real-Time Hospitality Outlet Management Application" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Pizza – Real-Time Hospitality Outlet Management Application</h3><p className="text-gray-400 mt-2">Engineered a tablet-optimized, real-time outlet operations and layout management dashboard, specifically designed to minimize operational friction in high-volume dining environments. Developed an interactive live floor-plan manager with persistent state updates and automated alert systems. Established a centralized telemetry pipeline for key performance metrics, successfully lowering seating friction intervals by 18%.</p></div>
            <div key="Trinity – Personalized Mental Health & Wellness Mobile Application" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Trinity – Personalized Mental Health & Wellness Mobile Application</h3><p className="text-gray-400 mt-2">Designed and developed a user-centric cross-platform mobile application dedicated to mental well-being, behavioral habits, and telehealth access. Created a smooth, interactive daily mood journaling module, incorporating specialized feedback and micro-interactions that boosted user retention by 22%. Implemented encrypted synchronization endpoints to ensure secure user data transmission and streamline clinical consultation booking.</p></div>
          </div></div></section>
  );
}
